# Generated by Django 2.0.2 on 2018-04-26 17:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='活动名')),
                ('desc', models.CharField(default='未知', max_length=300, verbose_name='活动描述')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='加入人数')),
                ('a_time', models.DateField(blank=True, max_length=50, null=True, verbose_name='活动时间')),
                ('a_addr', models.CharField(default='未知', max_length=100, verbose_name='活动地点')),
                ('image', models.ImageField(upload_to='activity/%y/%m', verbose_name='封面图')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='文章标题')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('head_img', models.ImageField(upload_to='article/%y/%m', verbose_name='标题图')),
                ('summary', models.CharField(max_length=25)),
                ('content', models.TextField(verbose_name='内容')),
                ('priority', models.IntegerField(default=1000, verbose_name='优先级')),
                ('com_nums', models.IntegerField(default=0, verbose_name='评论数')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏人数')),
            ],
            options={
                'verbose_name': '帖子',
                'verbose_name_plural': '帖子',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='图片名')),
                ('url', models.ImageField(upload_to='picture/%y/%m', verbose_name='图片内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
            },
        ),
        migrations.CreateModel(
            name='QuanZi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_name', models.CharField(max_length=50, unique=True, verbose_name='圈子名称')),
                ('desc', models.CharField(default='未知', max_length=140, verbose_name='圈子描述')),
                ('image', models.ImageField(upload_to='fandom/%y/%m', verbose_name='封面图')),
                ('tag', models.CharField(choices=[('ys', '影视'), ('gs', '歌手'), ('zy', '综艺')], max_length=2, verbose_name='标签')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_banner', models.BooleanField(default=False, verbose_name='是否轮播')),
                ('quan_tag', models.CharField(default='', max_length=10, verbose_name='圈子标签')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='关注人数')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击数')),
            ],
            options={
                'verbose_name': '圈子',
                'verbose_name_plural': '圈子',
            },
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.CharField(max_length=100, unique=True, verbose_name='名字')),
                ('constellation', models.CharField(default='未知', max_length=100, verbose_name='星座')),
                ('Bloodtype', models.CharField(default='未知', max_length=100, verbose_name='血型')),
                ('height', models.CharField(default='未知', max_length=100, verbose_name='身高')),
                ('birth', models.DateField(verbose_name='生日')),
                ('birthadd', models.CharField(default='未知', max_length=100, verbose_name='出生地')),
                ('himage', models.ImageField(upload_to='star_head_img/%y/%m', verbose_name='头像')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
            ],
            options={
                'verbose_name': '明星资料',
                'verbose_name_plural': '明星资料',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='视频名')),
                ('url', models.FileField(upload_to='video/%y/%m', verbose_name='视频内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('desc', models.CharField(default='未知', max_length=300, verbose_name='视频描述')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('q_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fandom.QuanZi', verbose_name='所属圈子')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
            },
        ),
    ]
