# Generated by Django 2.0.2 on 2018-04-26 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fandom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_user', to=settings.AUTH_USER_MODEL, verbose_name='上传人'),
        ),
        migrations.AddField(
            model_name='quanzi',
            name='star',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='quanzi_star', to='fandom.Star', verbose_name='所属明星'),
        ),
        migrations.AddField(
            model_name='quanzi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quanzi_user', to=settings.AUTH_USER_MODEL, verbose_name='圈子管理员'),
        ),
        migrations.AddField(
            model_name='picture',
            name='q_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fandom.QuanZi', verbose_name='所属圈子'),
        ),
        migrations.AddField(
            model_name='picture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture_user', to=settings.AUTH_USER_MODEL, verbose_name='上传人'),
        ),
        migrations.AddField(
            model_name='article',
            name='q_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fandom.QuanZi', verbose_name='所属圈子'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='activity',
            name='q_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fandom.QuanZi', verbose_name='所属圈子'),
        ),
        migrations.CreateModel(
            name='BannerCourse',
            fields=[
            ],
            options={
                'verbose_name': '轮播圈子',
                'verbose_name_plural': '轮播圈子',
                'proxy': True,
                'indexes': [],
            },
            bases=('fandom.quanzi',),
        ),
    ]
